version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./filebrowser:/config
      - /mnt/nas/:/srv
    environment:
      - FILEBROWSER_CONFIG=/config/filebrowser.json
    networks:
      - filebrowser-net

networks:
  filebrowser-net:
    driver: bridge

